spring:
  application:
    name: backend

  datasource:
    url: "jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:freeedu}"
    username: "${DB_USER:freeedu}"
    password: "${DB_PASSWORD:freeedu_pass}"

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-description: "init"
    baseline-version: "0"
    locations:
      - classpath:db/migration
      - classpath:db/seed

  codec:
    max-in-memory-size: 3MB

  webflux:
    multipart:
      max-parts: 1
      max-headers-size: 16KB
      max-disk-usage-per-part: 2MB
    static-path-pattern: /uploads/**

  web:
    resources:
      static-locations: "file:uploads/"
      add-mappings: true

application:
  stt:
    base-url: "${STT_BASE_URL:http://localhost:8000}"
    min-score: "${STT_MIN_SCORE:0.85}"
  security:
    jwt:
      secret-key: "${JWT_SECRET_KEY:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}"
      expiration: "${JWT_EXPIRATION:86400000}"

server:
  port: 8080
