### Login as Admin (Store admin_token + auth_token)
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "identifier": "admin@freeedu.pl",
  "password": "password"
}

> {%
    client.global.set("admin_token", response.body.token);
    client.global.set("auth_token", response.body.token);
%}

### Login as Teacher (Store teacher_token)
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "identifier": "teacher@szkola.pl",
  "password": "password"
}

> {%
    client.global.set("teacher_token", response.body.token);
%}

### Login as Student (Store student_token)
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "identifier": "student@szkola.pl",
  "password": "password"
}

> {%
    client.global.set("student_token", response.body.token);
%}
