### Register Student (Requires Admin)
POST http://localhost:8080/api/v1/users/register
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "email": "student_test@example.com",
  "username": "student_test",
  "password": "password"
}

### Create Admin (Requires Admin)
POST http://localhost:8080/api/v1/users/admin
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "email": "admin_test@example.com",
  "username": "admin_test",
  "password": "password"
}

### Get User Details (Requires Admin, Teacher of student's group, or Owner)
GET http://localhost:8080/api/v1/users/1
Authorization: Bearer {{auth_token}}

### Get Current User Profile
GET http://localhost:8080/api/v1/users/me
Authorization: Bearer {{auth_token}}

### Change User Password (Requires Admin or Owner)
PUT http://localhost:8080/api/v1/users/1/password
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "oldPassword": "old",
  "newPassword": "new"
}

### Create Teacher (Requires Admin)
POST http://localhost:8080/api/v1/users/teacher
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "email": "teacher_test@example.com",
  "username": "teacher_test",
  "password": "password"
}

### Update User Profile (Requires Admin or Owner)
PUT http://localhost:8080/api/v1/users/1
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "email": "updated@example.com",
  "username": "updated_user"
}

### Delete User (Requires Admin or Owner)
DELETE http://localhost:8080/api/v1/users/1
Authorization: Bearer {{auth_token}}
