### Student routes

### Student dashboard
GET http://localhost:5173/student
Authorization: Bearer {{auth_token}}

### Student Progress View
GET http://localhost:5173/student/progress
Authorization: Bearer {{auth_token}}

### Lesson Solver
GET http://localhost:5173/student/lessons/:lessonId
Authorization: Bearer {{auth_token}}

### Student Lesson Result View
GET http://localhost:5173/student/lessons/:lessonId/result
Authorization: Bearer {{auth_token}}

